version: '3.7'

services:
  database:
    buid: ./postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    networks:
      - my-network

  backend:
    build: ./simple-api-student-main
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_HOST: database
    depends_on:
      - database
    networks:
      - my-network

  httpd:
    build: ./html
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - my-network

  frontend:
    build: ./devops-front-main
    ports:
      - "9090:80"
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network:
