---
# tasks file for roles/launch_proxy
- name: Run the proxy container
  docker_container:
    name: httpd
    image: mattiiaass/tp-devops-httpd:latest
    ports:
      - "80:80"
    networks:
      - name: my-network
    pull: true
