---
# tasks file for roles/launch_app
- name: Run the application container
  docker_container:
    name: backend
    image: mattiiaass/tp-devops-simple-api:latest
    env:
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      POSTGRES_DB: "{{ postgres_db }}"
      POSTGRES_HOST: "{{ postgres_host }}"
    networks:
      - name: my-network
    pull: true