name: CI devops 2023

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and test with Maven
        working-directory: ./simple-api-student-main 
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=matiascpe -Dsonar.organization=MatiasCPE_TP_Github_Actions -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./simple-api/pom.xml


  build-and-push-docker-image:
    needs: test-backend  # Assurez-vous que ce job dépend du job de test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.5.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api-student-main  # Chemin vers le dossier contenant le Dockerfile du backend
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}  # Pousse l'image seulement si le commit est sur la branche main
      - name: Build and push postgres image
        uses: docker/build-push-action@v3
        with:
          context: ./postgres  # Chemin vers le dossier contenant le Dockerfile du backend
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-postgres:latest
          push: ${{ github.ref == 'refs/heads/main' }}  # Pousse l'image seulement si le commit est sur la branche main
      - name: Build and push httpd image
        uses: docker/build-push-action@v3
        with:
          context: ./html  # Chemin vers le dossier contenant le Dockerfile du backend
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}  # Pousse l'image seulement si le commit est sur la branche main  